name: Artifact Release

on:
  push:
  workflow_dispatch:
    inputs:
      release:
        description: "Release (e.g., v0.22.0)"
        required: true

permissions: read-all

jobs:
  info:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event.inputs.release }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Artifact
        run: |
          set -x -e
          COMMIT=28a16b480e58979ce11f8252092d5a34834ece9b #$(git rev-list -n 1 ${RELEASE})
          WORKFLOW=$(curl -s \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/tensorflow/io/actions/workflows \
              | jq -r '.workflows | map(select(.name=="GitHub CI"))[0].id')
          RUN=$(curl -s \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/tensorflow/io/actions/workflows/${WORKFLOW}/runs \
              | jq -r ".workflow_runs | map(select(.head_sha==\"${COMMIT}\"))[0].id")
          ARCHIVE=$(curl -s \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/tensorflow/io/actions/runs/${RUN}/artifacts \
              | jq -r '.artifacts | map(select(.name=="tensorflow-io-release"))[0].archive_download_url')
          echo "::set-output name=commit::${COMMIT}"
          echo "::set-output name=archive::${ARCHIVE}"
        id: artifact
    outputs:
      commit: ${{ steps.artifact.outputs.commit }}
      archive: ${{ steps.artifact.outputs.archive }}

  test:
    runs-on: ubuntu-latest
    needs:
      - info
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ needs.info.outputs.commit }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download Artifact2
        run: |
          set -x -e
          require=$(grep 'require = ' tensorflow_io/python/ops/version_ops.py | sed -E 's@^.*require = "@@g' | sed -E 's@".*$@@g')
      - name: Download Artifact
        run: |
          set -x -e
          curl ${{ needs.info.outputs.archive }}
          curl -s -vv \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -o archive.zip \
            ${{ needs.info.outputs.archive }}
          head archive.zip
          ls -la
          unzip archive.zip
          ls -la

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - info
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ needs.info.outputs.commit }}
      - name: Download Artifact
        run: |
          set -x -e
          curl ${{ needs.info.outputs.archive }}
          curl -s -vv \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -o archive.zip \
            ${{ needs.info.outputs.archive }}
          head archive.zip
          ls -la
          unzip archive.zip
          ls -la
